name: surf_flutter_courses_template
description: Our courses' template.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  json_annotation: ^4.8.1
  shake: ^2.2.0
  get_it: ^7.7.0
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  retrofit_generator: '>=7.0.0 <8.0.0'

flutter:
  uses-material-design: true

  assets:
  - assets/
